### ISSUE TITLE
HTTP redirection loop error

### ISSUE THREAD

**Issue by aliyeysides** [emberjs/ember-rails#427]
When I run `rails new ember-rails-blog -m http://emberjs.com/edge_template.rb -T -d postgresql`
I get the following error: 
```
     apply  http://emberjs.com/edge_template.rb
/usr/lib/ruby/1.9.1/open-uri.rb:224:in `open_loop': HTTP redirection loop: http://emberjs.com/edge_template.rb (RuntimeError)
```

There was someone else who had a similar issue on stackoverflow and they used sudo to prefix the command but that won't work for me. I also tried sudo -s before any commands. 

The rails project is still made but with no ember components included. Just a boilerplate rails skeleton.

Here is the rest of the stack trace:
```
       apply  http://emberjs.com/edge_template.rb
/usr/lib/ruby/1.9.1/open-uri.rb:224:in `open_loop': HTTP redirection loop: http://emberjs.com/edge_template.rb (RuntimeError)
from /usr/lib/ruby/1.9.1/open-uri.rb:146:in `open_uri'
	from /usr/lib/ruby/1.9.1/open-uri.rb:677:in `open'
	from /usr/lib/ruby/1.9.1/open-uri.rb:33:in `open'
	from /usr/lib/ruby/vendor_ruby/thor/actions.rb:218:in `apply'
	from /usr/lib/ruby/vendor_ruby/rails/generators/app_base.rb:101:in `apply_rails_template'
	from (eval):1:in `apply_rails_template'
	from /usr/lib/ruby/vendor_ruby/thor/command.rb:27:in `run'
	from /usr/lib/ruby/vendor_ruby/thor/invocation.rb:121:in `invoke_command'
	from /usr/lib/ruby/vendor_ruby/thor/invocation.rb:128:in `block in invoke_all'
	from /usr/lib/ruby/vendor_ruby/thor/invocation.rb:128:in `each'
	from /usr/lib/ruby/vendor_ruby/thor/invocation.rb:128:in `map'
	from /usr/lib/ruby/vendor_ruby/thor/invocation.rb:128:in `invoke_all'
	from /usr/lib/ruby/vendor_ruby/thor/group.rb:232:in `dispatch'
	from /usr/lib/ruby/vendor_ruby/thor/base.rb:440:in `start'
	from /usr/lib/ruby/vendor_ruby/rails/commands/application.rb:43:in `<top (required)>'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/lib/ruby/vendor_ruby/rails/cli.rb:15:in `<top (required)>'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/bin/rails:9:in `<main>'
```

**Comment by aliyeysides** [comment]
Ok so I actually got it working now with sudo, but I get another error after the template was applied saying:
```
/usr/bin/ruby1.9.1: No such file or directory -- /usr/share/rubygems-integration/1.9.1/gems/bundler-1.3.5/bin/bundle (LoadError)
```
Also probably worthy of noting that I'm using Ubuntu 14.04

**Comment by tricknotes** [comment]
It seems you haven't install [bundler](http://bundler.io/) on your local.
Can you try `gem install bundler` ?

**Comment by tricknotes** [comment]
I'm closing this. But when it isn't solved against https://github.com/emberjs/ember-rails/issues/427#issuecomment-69535257, please ping me.

**Comment by dylandechant** [comment]
having the same problem, sudo didn't work, i also have bundler installed

**Comment by tricknotes** [comment]
hmm, it is strange...
I need a more debuggable info.

@dylandechant 
Could you tell me the result of following command?

```
curl -v http://emberjs.com/edge_template.rb
```

**Comment by aliyeysides** [comment]
I tried it from scratch and it worked, for some reason if I put a -d flag on rails to change the database it wouldn't work. I just did rails new without the -d using sudo -s and it worked

**Comment by tricknotes** [comment]
It seems an GitHub pages' issue.
NOTE: emberjs.com is hosted on GitHub pages

It sometimes (not always) returns 302 for some reasons when `/edge_template.rb` is requested.
``` 
$ curl -vIL http://emberjs.com/edge_template.rb
* Adding handle: conn: 0x7f9ce3803a00
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 0 (0x7f9ce3803a00) send_pipe: 1, recv_pipe: 0
* About to connect() to emberjs.com port 80 (#0)
*   Trying 192.30.252.153...
* Connected to emberjs.com (192.30.252.153) port 80 (#0)
> HEAD /edge_template.rb HTTP/1.1
> User-Agent: curl/7.30.0
> Host: emberjs.com
> Accept: */*
> 
< HTTP/1.1 302 Found
HTTP/1.1 302 Found
< Connection: close
Connection: close
< Pragma: no-cache
Pragma: no-cache
< cache-control: no-cache
cache-control: no-cache
< Location: /edge_template.rb
Location: /edge_template.rb

< 
* Closing connection 0
* Issue another request to this URL: 'http://emberjs.com/edge_template.rb'
* About to connect() to emberjs.com port 80 (#1)
*   Trying 192.30.252.153...
* Adding handle: conn: 0x7f9ce4002200
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 1 (0x7f9ce4002200) send_pipe: 1, recv_pipe: 0
* Connected to emberjs.com (192.30.252.153) port 80 (#1)
> HEAD /edge_template.rb HTTP/1.1
> User-Agent: curl/7.30.0
> Host: emberjs.com
> Accept: */*
> 
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
* Server GitHub.com is not blacklisted
< Server: GitHub.com
Server: GitHub.com
< Date: Fri, 23 Jan 2015 05:14:48 GMT
Date: Fri, 23 Jan 2015 05:14:48 GMT
< Content-Type: application/octet-stream
Content-Type: application/octet-stream
< Content-Length: 1805
Content-Length: 1805
< Last-Modified: Mon, 12 Jan 2015 16:11:03 GMT
Last-Modified: Mon, 12 Jan 2015 16:11:03 GMT
< Expires: Fri, 23 Jan 2015 05:24:48 GMT
Expires: Fri, 23 Jan 2015 05:24:48 GMT
< Cache-Control: max-age=600
Cache-Control: max-age=600
< Accept-Ranges: bytes
Accept-Ranges: bytes
```

I don't know when and why it caused.
