### ISSUE TITLE
Rails Operations in AWS EC2/ElasticBeanstalk Environments Fail from Permissions Set on /tmp/ember-rails Files

### ISSUE THREAD

**Issue by uhrohraggy** [emberjs/ember-rails#429]
For Amazon EC2 instances, at least the ones created via ElasticBeanstalk, the files that get dropped into tmp folder (tmp/ember-rails/ember.js and tmp/ember-rails/ember-data.js) have file permissions that prevent most operations involving Rails to fail, in my case either rake:migrate or use of delayed_job daemons. The tmp file is not deployed between environments, and of course, they get generated whenever the Rails application is initialized, which makes sense. I can't tell if it's Amazon or just the default permissions on the gem's copy of the files that are determining permissions, and perhaps it's me being ignorant, but in order to fix this, I have to set chmod 766 on each file. I don't think it's a bug, but is there a better alternative?

`sudo chmod 766 tmp/ember-rails/ember.js && sudo chmod 766 tmp/ember-rails/ember-data.js`
RAILS_ENV=production script/delayed_job restart

```
[ec2-user@ip-10-0-10-42 current]$ rake db:migrate
rake aborted!
Errno::EACCES: Permission denied - /var/app/current/tmp/ember-rails/ember.js
/var/app/current/config/environment.rb:6:in `<top (required)>'
Tasks: TOP => db:migrate => environment
(See full trace by running task with --trace)
```
```
Amazon Linux version 2014.09 is available.
[ec2-user@ip-10-0-0-111 ~]$ cd /var/app/current
[ec2-user@ip-10-0-0-111 current]$ RAILS_ENV=production script/delayed_job stop
/var/app/current/config/environments/production.rb:114: warning: already initialized constant VERIFY_PEER
/usr/share/ruby/1.9/fileutils.rb:1371:in `initialize': Permission denied - /var/app/current/tmp/ember-rails/ember.js (Errno::EACCES)
	from /usr/share/ruby/1.9/fileutils.rb:1371:in `open'
	from /usr/share/ruby/1.9/fileutils.rb:1371:in `block in copy_file'
	from /usr/share/ruby/1.9/fileutils.rb:1370:in `open'
	from /usr/share/ruby/1.9/fileutils.rb:1370:in `copy_file'
	from /usr/share/ruby/1.9/fileutils.rb:477:in `copy_file'
	from /usr/share/ruby/1.9/fileutils.rb:396:in `block in cp'
	from /usr/share/ruby/1.9/fileutils.rb:1515:in `block in fu_each_src_dest'
	from /usr/share/ruby/1.9/fileutils.rb:1531:in `fu_each_src_dest0'
	from /usr/share/ruby/1.9/fileutils.rb:1513:in `fu_each_src_dest'
	from /usr/share/ruby/1.9/fileutils.rb:395:in `cp'
	from /usr/share/ruby/1.9/gems/1.9.1/gems/ember-rails-0.15.0/lib/ember_rails.rb:31:in `block in <class:Railtie>'
	from /usr/share/ruby/1.9/gems/1.9.1/gems/railties-3.2.19/lib/rails/initializable.rb:30:in `instance_exec'
	from /usr/share/ruby/1.9/gems/1.9.1/gems/railties-3.2.19/lib/rails/initializable.rb:30:in `run'
	from /usr/share/ruby/1.9/gems/1.9.1/gems/railties-3.2.19/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /usr/share/ruby/1.9/gems/1.9.1/gems/railties-3.2.19/lib/rails/initializable.rb:54:in `each'
	from /usr/share/ruby/1.9/gems/1.9.1/gems/railties-3.2.19/lib/rails/initializable.rb:54:in `run_initializers'
	from /usr/share/ruby/1.9/gems/1.9.1/gems/railties-3.2.19/lib/rails/application.rb:136:in `initialize!'
	from /usr/share/ruby/1.9/gems/1.9.1/gems/railties-3.2.19/lib/rails/railtie/configurable.rb:30:in `method_missing'
	from /var/app/current/config/environment.rb:6:in `<top (required)>'
	from /usr/share/rubygems1.9/rubygems/custom_require.rb:36:in `require'
	from /usr/share/rubygems1.9/rubygems/custom_require.rb:36:in `require'
	from script/delayed_job:3:in `<main>'
[ec2-user@ip-10-0-0-111 current]$ sudo chmod 766 tmp/ember-rails/ember.js && sudo chmod 766 tmp/ember-rails/ember-data.js && RAILS_ENV=production script/delayed_job stop
```

**Comment by tricknotes** [comment]
Who is the owner of `tmp/ember-rails/ember.js` and `tmp/ember-rails/ember-data.js` ?
I guess some process that is not a rails user boots rails application.(It may background jobs)

Can you check such process is there?
If it exist, can you change its owner?

**Comment by uhrohraggy** [comment]
Ahh, that makes sense. SSH is done with ec2-user by default, and when trying to run those same commands in terminal fails, whereas during deployment they're perfectly fine. So not really an issue then, since except in debugging, I'm of the opinion this should be handled via OpsWorks or deployment hook files anyway. Thanks for looking into this.

Local:
```
uhrohraggy@deusexmachina:~/Documents/apps/mvp$ ls -l tmp/ember-rails/
total 1912
-rw-r--r-- 1 uhrohraggy uhrohraggy  374458 Jan 14 18:48 ember-data.js
-rw-r--r-- 1 uhrohraggy uhrohraggy 1577118 Jan 14 18:48 ember.js
```

AWS EC2:
```
[ec2-user@ip-10-0-0-42 ~]$ cd /var/app/current
[ec2-user@ip-10-0-0-42 current]$ ls -l tmp/ember-rails/
total 1868
-rw-r--r-- 1 webapp webapp  367066 Jan 14 17:35 ember-data.js
-rw-r--r-- 1 webapp webapp 1541642 Jan 14 17:35 ember.js
```
